<?php
define('Web_Name','Ctcms管理系统'); //站点名称  
define('Web_Url','www.ctcms.com'); //站点域名  
define('Web_Path','/'); //站点路径  
define('Web_Off',0);  //网站开关  
define('Web_Onneir','');  //网站关闭内容  
define('Web_Pc',1);  //电脑访问开关  
define('Web_Mode',2);  //网站运行模式  
define('Web_Icp','沪ICP备06000000号');  //网站ICP  
define('Web_Count','');  //统计代码  
define('Web_Title','Ctcms视频系统'); //SEO-标题  
define('Web_Keywords',''); //SEO-Keywords  
define('Web_Description',''); //SEO-description  
define('Web_Skin','default'); //网站默认模板  
define('Admin_QQ','82848860');  //站长QQ  
define('Admin_Mail','admin@qq.com');  //站长EMAIL  
define('Admin_Code','111');  //后台验证码  
define('Admin_Log_Day',30);  //后台登陆日志保存天数  
define('Admin_Log_Ip','');  //允许访问后台的IP列表  
define('Cache_Is',0);  //缓存开关  
define('Cache_Time',600);  //缓存时间  
define('Base_Path','/packs/'); //附件路径，包含后台css、js、images  
define('Weixin','ctcms');  //微信号    
define('Weixin_Url','http://www.ctcms.cn');  //微信号链接
define('Weixin_Token','test');  //微信自动回复token
define('Wap_Is',0);  //手机版开关
define('Wap_Url','');  //手机版地址
define('Wap_Skin','default');  //手机版模版
define('Wap_User_Skin','default');  //手机版会员模版
define('User_Off',0);  //会员开关  
define('User_Onneir','');  //会员关闭内容  
define('User_Reg_Cion',10);  //会员注册赠送金币  
define('User_Log_Cion',1);  //会员注册赠送金币  
define('User_Qd_Cion',0);  //会员注册赠送金币  
define('User_Skin','default'); //会员默认模板  
define('User_Fc_Off',1);  //三级分销开关  
define('User_Fc_Tx',100);  //分成最少提现额  
define('User_Fc_1',5);  //一级分销分成比例  
define('User_Fc_2',3);  //二级分销分成比例  
define('User_Fc_3',1);  //三级分销分成比例  
define('Uri_Mode',0);  //是否启用Url路由  
define('Uri_List','type/[cid]/[page].html');  //分类页路由规则  
define('Uri_Show','show/[id].html');  //内容页路由规则  
define('Uri_Play','play/[id]~[zu]~[ji].html');  //播放页路由规则  
define('Uri_Comm','comm/[cid]~[page].html');  //圈子分类路由规则  
define('Uri_Article','article/[id]~[page].html');  //圈子内容路由规则  
define('Uri_Topic','topic/[page].html');  //专题路由规则  
define('Uri_Topic_Show','topic/show~[id].html');  //专题内容路由规则  
define('Web_Diqu','大陆|香港|台湾|美国|日本|韩国|其他');  //地区  
define('Web_Yuyan','国语|粤语|台语|英语|日语|韩语|其他');  //语言  
define('Web_Year','2019|2018|2017|2016|2015|2014|2013|2012|2011|2010|2009|2008|更早');  //年份  
define('Web_Type','1#传记|喜剧|剧情|枪战|恐怖|励志|歌舞|犯罪|偶像|悬疑|爱情|惊悚|纪录|青春|科幻|冒险|魔幻|丧尸|动作|幻想|战争|情色|血腥|西部|童话|暴力|古装|灾难|谍战|生活|讽刺|同性
2#古装|武侠|警匪|军事|神话|悬疑|科幻|历史|儿童|言情|农村|谍战|偶像|家庭|都市|时装
15#热血|格斗|恋爱|美少女|校园|搞笑|LOLI|神魔|机战|科幻|真人|青春|魔法|神话|冒险|运动|竞技|童话|亲子|教育|励志|剧情|社会|历史|战争
4#脱口秀|真人秀|选秀|美食|旅游|汽车|访谈|纪实|搞笑|时尚|晚会|理财|演唱会|益智|音乐|舞蹈|游戏|生活');  //类型  
define('Web_Pl','{pl}');  //评论代码  
define('Gbook_Is',1);  //留言开关  
define('Gbook_Log',0);  //留言需要登陆  
define('Gbook_Sh',0);  //留言需要审核  
define('Gbook_Str','妈的|垃圾|去死');  //留言过滤关键字  
define('Ftp_Is',0);  //FTP远程附件开关  
define('Ftp_Token','234');  //贴图库Token  
define('Ftp_Pid','12342');  //贴图库相册ID  
define('Ftp_Url','http://api.zzshj.com/ceshi/');  //FTP图片远程访问地址  
define('Ftp_Server','web.zzshj.com');  //FTP链接IP  
define('Ftp_User','ceshi1');  //FTP连接账号  
define('Ftp_Pass','ceshi1');  //FTP链接密码  
define('Ftp_Port','21');  //FTP链接端口  
define('Ftp_Ive',FALSE);  //FTP是否使用被动模式  
define('Ftp_Dir','');  //FTP默认目录  
define('IS_Api',1);  //是否启用资源api采集
define('Cj_Add','cid');  //采集入库重复规则
define('Cj_Edit','addtime,url,state');  //采集二次更新