<?php
define('Zhuan_Is',1);
define('Zhuan_Kbps','');
define('Zhuan_Size','');
define('Zhuan_Time',10);
define('Zhuan_Path','./vod/');
define('Zhuan_Url','');
define('Zhuan_M3u8_Url','');
define('Zhuan_Sy_Is',0);
define('Zhuan_Sy_Pos',0);
define('Zhuan_Sy_Lt','5:5');
define('Zhuan_Sy_Pic','./packs/ffmpeg/logo.png');
define('Zhuan_Jpg_Size','');
define('Zhuan_Jpg_Num',10);
define('Zhuan_Jpg_Time',3);
define('Zhuan_Sk',1);
define('Zhuan_Sk_Type',1);
define('Zhuan_Sk_Time',60);
define('Zhuan_Sk_Nums',3);